routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a given Closure or controller and enjoy the fresh air.
|
*/

/*
|--------------------------------------------------------------------------
| Welcome Page
|--------------------------------------------------------------------------
*/

Route::get('/', 'PagesController@home');

/*
|--------------------------------------------------------------------------
| Login/ Logout/ Password
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Registration & Activation
|--------------------------------------------------------------------------
*/
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::get('activate/token/{token}', 'Auth\ActivateController@activate');
Route::group(['middleware' => ['auth']], function () {
    Route::get('activate', 'Auth\ActivateController@showActivate');
    Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['auth', 'active']], function () {

    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('/dashboard', 'PagesController@dashboard');

    /*
    |--------------------------------------------------------------------------
    | Team Routes
    |--------------------------------------------------------------------------
    */

    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');

    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

        Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

        /*
        |--------------------------------------------------------------------------
        | Users
        |--------------------------------------------------------------------------
        */
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');

        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

        /*
        |--------------------------------------------------------------------------
        | Time Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('times', 'TimesController', ['except' => ['show']]);
        Route::post('times/search', [
            'as' => 'times.search',
            'uses' => 'TimesController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | Evento Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('eventos', 'EventosController', ['except' => ['show']])->names('admin.eventos');
        Route::get('eventos/{id}/copy', 'EventosController@copy')->name('admin.eventos.copy');
        Route::post('eventos/search', [
            'as' => 'admin.eventos.search',
            'uses' => 'EventosController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | ListaNegra Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('lista_negras', 'ListaNegrasController', ['except' => ['show']]);
        Route::get('lista_negras/server/sync', 'ListaNegrasController@sync')->name('lista_negras.sync');
        Route::post('lista_negras/search', [
            'as' => 'lista_negras.search',
            'uses' => 'ListaNegrasController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | RegistroEvento Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('registro_eventos', 'RegistroEventosController', ['except' => ['destroy']])->names('admin.registro_eventos');
        Route::post('registro_eventos/search', [
            'as' => 'admin.registro_eventos.search',
            'uses' => 'RegistroEventosController@search'
        ]);
        Route::get('registro_eventos/valid/ingress/valid-ingress', [
            'as' => 'admin.registro_eventos.search.view',
            'uses' => 'RegistroEventosController@searchView'
        ]);


        /*
        |--------------------------------------------------------------------------
        | Estadio Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('estadios', 'EstadiosController', ['except' => ['show']]);
        Route::post('estadios/search', [
            'as' => 'estadios.search',
            'uses' => 'EstadiosController@search'
        ]);
    });

    /*
    |--------------------------------------------------------------------------
    | RegistroEvento Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('registro_eventos', 'RegistroEventosController');
    Route::get('registro_eventos', 'RegistroEventosController@index')->name('pagseguro.redirect');
    Route::post('registro_eventos/search', [
        'as' => 'registro_eventos.search',
        'uses' => 'RegistroEventosController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Dependete Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('dependetes', 'DependetesController', ['except' => ['show']]);
    Route::post('dependetes/search', [
        'as' => 'dependetes.search',
        'uses' => 'DependetesController@search'
    ]);




});

/*
|--------------------------------------------------------------------------
| Evento Routes
|--------------------------------------------------------------------------
*/
Route::resource('eventos', 'EventosController', ['only' => ['show']]);
Route::post('eventos/search', [
    'as' => 'eventos.search',
    'uses' => 'EventosController@search'
]);

Route::post('/pagseguro/notification', [
    'uses' => '\laravel\pagseguro\Platform\Laravel5\NotificationController@notification',
    'as' => 'pagseguro.notification',
]);

app/Models/Dependete.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Dependete extends Model
{
    use SoftDeletes;

    public $table = "dependetes";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
		'id',
		'nome',
		'email',
		'data_nascimento',
		'cpf',
		'user_id',

    ];

    public static $rules = [
        // create rules
        'nome' => 'required',
        'email' => 'required',
        'cpf' => 'required|cpf',
        'data_nascimento' => 'required|date_format:Y-m-d',
        'user_id' => 'required',
    ];


    public function getDependentes($id) {
        return $this->where('user_id', $id)->get();
    }

    // Dependete 
}

app/Http/Controllers/DependetesController.php
<?php

namespace App\Http\Controllers;

use App\Services\ListaNegraService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\DependeteService;
use App\Http\Requests\DependeteCreateRequest;
use App\Http\Requests\DependeteUpdateRequest;
use Illuminate\Support\Facades\Config;

/**
 * @property DependeteService service
 */
class DependetesController extends Controller
{
    /**
     * @var ListaNegraService
     */
    private $listaNegraService;

    /**
     * DependetesController constructor.
     * @param DependeteService $dependete_service
     * @param ListaNegraService $listaNegraService
     */
    public function __construct(DependeteService $dependete_service, ListaNegraService $listaNegraService)
    {
        $this->service = $dependete_service;
        $this->listaNegraService = $listaNegraService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dependetes = $this->service->paginated();
        return view('dependetes.index')->with('dependetes', $dependetes);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $dependetes = $this->service->search($request->search);
        return view('dependetes.index')->with('dependetes', $dependetes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dependetes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  DependeteCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DependeteCreateRequest $request)
    {
        if(($this->listaNegraService->isValid($request->cpf))) {
            return redirect(route('dependetes.create'))
                ->withErrors('CPF bloqueado, entre em contato com o <a target="_blank" href="mailto:'.Config::get('mail.from.address').'">adiministrador</a>.')
                ->withInput($request->input());
        }

        if($this->service->paginated()->count() >= auth()->user()->meta->depedente) {
            return redirect(route('dependetes.create'))
                ->withErrors('Limite de dependente excedido, entre em contato com o <a target="_blank" href="mailto:'.Config::get('mail.from.address').'">adiministrador</a>.')
                ->withInput($request->input());
        }

        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('dependetes.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('dependetes.index'))->withErrors('Failed to create');
    }

    /**
     * Display the dependete.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dependete = $this->service->find($id);
        return view('dependetes.show')->with('dependete', $dependete);
    }

    /**
     * Show the form for editing the dependete.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dependete = $this->service->find($id);
        return view('dependetes.edit')->with('dependete', $dependete);
    }

    /**
     * Update the dependetes in storage.
     *
     * @param  DependeteUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DependeteUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->withErrors('Failed to update');
    }

    /**
     * Remove the dependetes from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('dependetes.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('dependetes.index'))->withErrors('Failed to delete');
    }
}

resources/views/dependetes/create.blade.php
@extends('layouts.app')

@section('pageTitle') Dependentes &raquo; Criar @stop

@section('content')
    <div class="col-md-6 m-auto">
        <div class="card">
            <div class="card-header">
                <div class="col-md-12">
                    <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                        {!! Form::open(['route' => 'dependetes.search']) !!}
                        <input class="form-control form-inline pull-right" name="search" placeholder="Procurar">
                        {!! Form::close() !!}
                    </div>
                    <h1 class="pull-left">Dependentes: Criar</h1>
                </div>
            </div>
            <div class="card-body">
                <div class="col-md-12">

                    {!! Form::open(['route' => 'dependetes.store']) !!}
                    <div class="form-row raw-margin-bottom-15">
                        @form_maker_array([
                        'nome' => ['type' => 'string', 'alt_name' => 'Nome'],
                        'email' => ['type' => 'string', 'alt_name' => 'E-mail'],
                        ])
                    </div>
                    <div class="form-row raw-margin-bottom-15">
                        @form_maker_array([
                        'cpf' => ['type' => 'string', 'alt_name' => 'CPF'],
                        'data_nascimento' => ['type' => 'date', 'alt_name' => 'Data de Nascimento'],
                        ])
                    </div>
                    @form_maker_array([
                    'user_id' => ['type' => 'hidden', 'default_value' => auth()->user()->id],
                    ])
                    {!! Form::submit('Salvar', ['class' => 'btn btn-primary pull-right']) !!}
                    <a href="{{ url('dependetes') }}" class="btn btn-secondary"> Voltar</a>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>

@stop

resources/views/dependetes/edit.blade.php
@extends('layouts.app')

@section('pageTitle') Dependetes &raquo; Editar @stop

@section('content')
<div class="col-md-6 m-auto">
    <div class="card">
        <div class="card-header">
            <div class="col-md-12">
                <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                    {!! Form::open(['route' => 'dependetes.search']) !!}
                    <input class="form-control form-inline pull-right" name="search" placeholder="Procurar">
                    {!! Form::close() !!}
                </div>
                <h1 class="pull-left">Dependetes: Editar</h1>
                <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('dependetes.create') !!}">Adicionar novo</a>
            </div>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                {!! Form::model($dependete, ['route' => ['dependetes.update', $dependete->id], 'method' => 'patch']) !!}

                <div class="form-row raw-margin-bottom-15">
                    @form_maker_array($dependete, [
                    'nome' => ['type' => 'string', 'alt_name' => 'Nome'],
                    'email' => ['type' => 'string', 'alt_name' => 'E-mail'],
                    ])
                </div>
                <div class="form-row raw-margin-bottom-15">
                    @form_maker_array($dependete, [
                    'cpf' => ['type' => 'string', 'alt_name' => 'CPF'],
                    'data_nascimento' => ['type' => 'date', 'alt_name' => 'Data de Nascimento'],
                    ])
                </div>

                {!! Form::submit('Atualizar', ['class' => 'btn btn-primary pull-right']) !!}
                <a href="{{ url('dependetes') }}" class="btn btn-secondary"> Cancelar</a>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

@stop

resources/views/dependetes/index.blade.php
@extends('layouts.app')

@section('pageTitle') Dependente &raquo; Índice @stop

@section('content')
<div class="col-md-8 m-auto">
        <div class="card">
            <div class="card-header">
                <div class="col-md-12">
                    <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                        {!! Form::open(['route' => 'dependetes.search']) !!}
                        <input class="form-control form-inline pull-right" name="search" placeholder="Procurar">
                        {!! Form::close() !!}
                    </div>
                    <h1 class="pull-left">Dependente</h1>
                    <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('dependetes.create') !!}">Adicionar novo</a>
                </div>
            </div>

                <div class="card-body">
                    <div class="col-md-12">
                        @if ($dependetes->isEmpty())
                            <div class="well text-center">Nenhum dependete encontrado.</div>
                        @else
                            <table class="table table-striped">
                                <thead>
                                    <th>Nome</th>
                                    <th class="text-right" width="200px">Ação</th>
                                </thead>
                                <tbody>
                                    @foreach($dependetes as $dependete)
                                        <tr>
                                            <td>
                                                <a href="{!! route('dependetes.edit', [$dependete->id]) !!}">{{ $dependete->nome }}</a>
                                            </td>
                                            <td class="text-right">
                                                <form method="post" action="{!! route('dependetes.destroy', [$dependete->id]) !!}">
                                                    {!! csrf_field() !!}
                                                    {!! method_field('DELETE') !!}
                                                    <button class="btn btn-danger btn-sm float-right" type="submit" onclick="return confirm('Tem certeza de que deseja excluir este dependente?')"><i class="fa fa-trash"></i> Excluir</button>
                                                </form>
                                                <a class="btn btn-default btn-sm float-right raw-margin-right-16" href="{!! route('dependetes.edit', [$dependete->id]) !!}"><i class="fa fa-pencil"></i> Editar</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                    </div>
                </div>
           </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            {!! $dependetes; !!}
        </div>
    </div>

@stop

resources/views/dependetes/show.blade.php
@extends('dashboard', ['pageTitle' => 'Dependetes &raquo; Show'])

@section('content')

    <div class="container">
        <div class="col-md-12">

        <!-- Put fields here -->

        </div>
    </div>

@stop