routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a given Closure or controller and enjoy the fresh air.
|
*/

/*
|--------------------------------------------------------------------------
| Welcome Page
|--------------------------------------------------------------------------
*/

Route::get('/', 'PagesController@home');

/*
|--------------------------------------------------------------------------
| Login/ Logout/ Password
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Registration & Activation
|--------------------------------------------------------------------------
*/
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::get('activate/token/{token}', 'Auth\ActivateController@activate');
Route::group(['middleware' => ['auth']], function () {
    Route::get('activate', 'Auth\ActivateController@showActivate');
    Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['auth', 'active']], function () {

    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('/dashboard', 'PagesController@dashboard');

    /*
    |--------------------------------------------------------------------------
    | Team Routes
    |--------------------------------------------------------------------------
    */

    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');

    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

        Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

        /*
        |--------------------------------------------------------------------------
        | Users
        |--------------------------------------------------------------------------
        */
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');

        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

        /*
        |--------------------------------------------------------------------------
        | Time Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('times', 'TimesController', ['except' => ['show']]);
        Route::post('times/search', [
            'as' => 'times.search',
            'uses' => 'TimesController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | Evento Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('eventos', 'EventosController', ['except' => ['show']])->names('admin.eventos');
        Route::get('eventos/{id}/copy', 'EventosController@copy')->name('admin.eventos.copy');
        Route::post('eventos/search', [
            'as' => 'admin.eventos.search',
            'uses' => 'EventosController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | ListaNegra Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('lista_negras', 'ListaNegrasController', ['except' => ['show']]);
        Route::get('lista_negras/server/sync', 'ListaNegrasController@sync')->name('lista_negras.sync');
        Route::post('lista_negras/search', [
            'as' => 'lista_negras.search',
            'uses' => 'ListaNegrasController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | RegistroEvento Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('registro_eventos', 'RegistroEventosController', ['except' => ['destroy']])->names('admin.registro_eventos');
        Route::post('registro_eventos/search', [
            'as' => 'admin.registro_eventos.search',
            'uses' => 'RegistroEventosController@search'
        ]);
        Route::get('registro_eventos/valid/ingress/valid-ingress', [
            'as' => 'admin.registro_eventos.search.view',
            'uses' => 'RegistroEventosController@searchView'
        ]);


        /*
        |--------------------------------------------------------------------------
        | Estadio Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('estadios', 'EstadiosController', ['except' => ['show']]);
        Route::post('estadios/search', [
            'as' => 'estadios.search',
            'uses' => 'EstadiosController@search'
        ]);
    });

    /*
    |--------------------------------------------------------------------------
    | RegistroEvento Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('registro_eventos', 'RegistroEventosController');
    Route::get('registro_eventos', 'RegistroEventosController@index')->name('pagseguro.redirect');
    Route::post('registro_eventos/search', [
        'as' => 'registro_eventos.search',
        'uses' => 'RegistroEventosController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Dependete Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('dependetes', 'DependetesController', ['except' => ['show']]);
    Route::post('dependetes/search', [
        'as' => 'dependetes.search',
        'uses' => 'DependetesController@search'
    ]);




});

/*
|--------------------------------------------------------------------------
| Evento Routes
|--------------------------------------------------------------------------
*/
Route::resource('eventos', 'EventosController', ['only' => ['show']]);
Route::post('eventos/search', [
    'as' => 'eventos.search',
    'uses' => 'EventosController@search'
]);

Route::post('/pagseguro/notification', [
    'uses' => '\laravel\pagseguro\Platform\Laravel5\NotificationController@notification',
    'as' => 'pagseguro.notification',
]);

app/Http/Controllers/Admin/EventosController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\EventoService;
use App\Http\Requests\EventoCreateRequest;
use App\Http\Requests\EventoUpdateRequest;

/**
 * @property EventoService service
 */
class EventosController extends Controller
{
    public function __construct(EventoService $evento_service)
    {
        $this->service = $evento_service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $eventos = $this->service->paginated();
        return view('admin.eventos.index')->with('eventos', $eventos);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $eventos = $this->service->search($request->search);
        return view('admin.eventos.index')->with('eventos', $eventos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.eventos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  EventoCreateRequest $request
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function store(EventoCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('admin.eventos.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('admin.eventos.index'))->withErrors('Failed to create');
    }

    /**
     * Display the evento.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $evento = $this->service->find($id);
        return view('admin.eventos.show')->with('evento', $evento);
    }

    /**
     * Show the form for editing the evento.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $evento = $this->service->find($id);
        return view('admin.eventos.edit')->with('evento', $evento);
    }

    /**
     * Update the eventos in storage.
     *
     * @param  EventoUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EventoUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->withErrors('Failed to update');
    }

    /**
     * Update the eventos in storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function copy($id)
    {
        $model = $this->service->find($id);

        $result = $this->service->create($model->only([
            'status',
            'nome',
            'time_1_id',
            'time_2_id',
            'estadio_id',
            'quantidade_alta_valor',
            'quantidade_alta',
            'quantidade_baixa_valor',
            'quantidade_baixa',
            'quantidade_especial',
            'quantidade_especial_valor',
            'data_evento',
            'descricao',
            'foto',
        ]));

        if ($result) {
            return redirect(route('admin.eventos.edit', ['id' => $result->id]))->with('message', 'Successfully copy');
        }

        return redirect(route('admin.eventos.index'))->withErrors('Failed to copy');
    }

    /**
     * Remove the eventos from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('admin.eventos.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('admin.eventos.index'))->withErrors('Failed to delete');
    }
}

app/Http/Controllers/EventosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\EventoService;
use App\Http\Requests\EventoCreateRequest;
use App\Http\Requests\EventoUpdateRequest;

class EventosController extends Controller
{
    public function __construct(EventoService $evento_service)
    {
        $this->service = $evento_service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $eventos = $this->service->paginated();
        return view('eventos.index')->with('eventos', $eventos);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $eventos = $this->service->search($request->search);
        return view('eventos.index')->with('eventos', $eventos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('eventos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\EventoCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EventoCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('eventos.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('eventos.index'))->withErrors('Failed to create');
    }

    /**
     * Display the evento.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $evento = $this->service->find($id);
        return view('eventos.show')->with('evento', $evento);
    }

    /**
     * Show the form for editing the evento.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $evento = $this->service->find($id);
        return view('eventos.edit')->with('evento', $evento);
    }

    /**
     * Update the eventos in storage.
     *
     * @param  App\Http\Requests\EventoUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EventoUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->withErrors('Failed to update');
    }

    /**
     * Remove the eventos from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('eventos.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('eventos.index'))->withErrors('Failed to delete');
    }
}

resources/views/admin/eventos/create.blade.php
@extends('layouts.app')

@section('pageTitle') Eventos &raquo; Criar @stop

@section('content')
    <div class="col-md-6 m-auto">
        <div class="card">
            <div class="card-header">
                <div class="col-md-12">
                    <div class="float-right raw-margin-top-24 raw-margin-left-24">
                        {!! Form::open(['route' => 'admin.eventos.search']) !!}
                        <input class="form-control form-inline pull-right" name="search" placeholder="Procurar">
                        {!! Form::close() !!}
                    </div>
                    <h1 class="pull-left">Eventos: Criar</h1>
                </div>
            </div>
            <div class="card-body">
                <div class="col-md-12">

                    {!! Form::open(['route' => 'admin.eventos.store', 'files' => true]) !!}

                    <div class="form-row raw-margin-bottom-15">
                        @form_maker_array([
                        'nome' => ['type' => 'string'],
                        'data_evento' => ['type' => 'date', 'alt_name' => 'Data do Evento'],
                        ])
                    </div>

                    <div class="form-row raw-margin-bottom-15">
                        @form_maker_array([
                        'time_1_id' => ['type' => 'relationship', 'alt_name' => 'Time A', 'model' => 'App\Models\Time', 'label' => 'nome'],
                        'time_2_id' => ['type' => 'relationship', 'alt_name' => 'Time B', 'model' => 'App\Models\Time', 'label' => 'nome'],
                        'estadio_id' => ['type' => 'relationship', 'alt_name' => 'Estádio', 'model' => 'App\Models\Estadio', 'label' => 'nome'],
                        ])
                    </div>

                    <div class="form-row raw-margin-bottom-15">
                        @form_maker_array([
                        'quantidade_alta' => ['type' => 'number', 'alt_name' => 'Quantidade Alta'],
                        'quantidade_baixa' => ['type' => 'number', 'alt_name' => 'Quantidade Baixa'],
                        'quantidade_especial' => ['type' => 'number', 'alt_name' => 'Quantidade Especial'],
                        ])
                    </div>

                    <div class="form-row raw-margin-bottom-15">
                        @form_maker_array([
                        'quantidade_alta_valor' => ['type' => 'string', 'alt_name' => 'Valor Quantidade Alta'],
                        'quantidade_baixa_valor' => ['type' => 'string', 'alt_name' => 'Valor Quantidade Baixa'],
                        'quantidade_especial_valor' => ['type' => 'string', 'alt_name' => 'Valor Quantidade Especial'],
                        ])
                    </div>

                    <div class="form-row raw-margin-bottom-15">
                        @form_maker_array([
                        'descricao' => ['type' => 'text', 'alt_name' => 'Descriçao'],
                        'arquivo' => ['type' => 'file', 'alt_name' => 'Foto'],
                        ])
                    </div>

                    {!! Form::submit('Salvar', ['class' => 'btn btn-primary pull-right']) !!}
                    <a href="{{ url('admin/eventos') }}" class="btn btn-secondary"> Cancelar</a>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>

@stop

resources/views/admin/eventos/edit.blade.php
@extends('layouts.app')

@section('pageTitle') Eventos &raquo; Editar @stop

@section('content')
<div class="col-md-8 m-auto">
    <div class="card">
        <div class="card-header">
            <div class="col-md-12">
                <div class="float-right raw-margin-top-24 raw-margin-left-24 col-md-4">
                    <img src="{{ url($evento->foto) }}" alt="" class="float-right w-100">
                </div>
                <h1 class="pull-left">Eventos: Editar</h1>
            </div>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                {!! Form::model($evento, ['route' => ['admin.eventos.update', $evento->id], 'method' => 'patch', 'files' => true]) !!}

                <div class="form-row raw-margin-bottom-15">
                    @form_maker_array($evento, [
                    'nome' => ['type' => 'string'],
                    'data_evento' => ['type' => 'date', 'alt_name' => 'Data do Evento'],
                    ])
                </div>

                <div class="form-row raw-margin-bottom-15">
                    @form_maker_array($evento, [
                    'time_1_id' => ['type' => 'relationship', 'alt_name' => 'Time A', 'model' => 'App\Models\Time', 'label' => 'nome'],
                    'time_2_id' => ['type' => 'relationship', 'alt_name' => 'Time B', 'model' => 'App\Models\Time', 'label' => 'nome'],
                    'estadio_id' => ['type' => 'relationship', 'alt_name' => 'Estádio', 'model' => 'App\Models\Estadio', 'label' => 'nome'],
                    ])
                </div>

                <div class="form-row raw-margin-bottom-15">
                    @form_maker_array($evento, [
                    'quantidade_alta' => ['type' => 'number', 'alt_name' => 'Quantidade Alta'],
                    'quantidade_baixa' => ['type' => 'number', 'alt_name' => 'Quantidade Baixa'],
                    'quantidade_especial' => ['type' => 'number', 'alt_name' => 'Quantidade Especial'],
                    ])
                </div>

                <div class="form-row raw-margin-bottom-15">
                    @form_maker_array($evento, [
                    'quantidade_alta_valor' => ['type' => 'string', 'alt_name' => 'Valor Quantidade Alta'],
                    'quantidade_baixa_valor' => ['type' => 'string', 'alt_name' => 'Valor Quantidade Baixa'],
                    'quantidade_especial_valor' => ['type' => 'string', 'alt_name' => 'Valor Quantidade Especial'],
                    ])
                </div>

                <div class="form-row raw-margin-bottom-15">
                    @form_maker_array($evento, [
                    'descricao' => ['type' => 'text', 'alt_name' => 'Descriçao'],
                    'arquivo' => ['type' => 'file', 'alt_name' => 'Foto'],
                    ])
                </div>

                {!! Form::submit('Atualizar', ['class' => 'btn btn-primary pull-right']) !!}
                <a href="{{ url('admin/eventos') }}" class="btn btn-secondary">Voltar</a>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

@stop

resources/views/admin/eventos/index.blade.php
@extends('layouts.app')

@section('pageTitle') Eventos &raquo; Índice @stop

@section('content')
<div class="col-md-8 m-auto">
        <div class="card">
            <div class="card-header">
                <div class="col-md-12">
                    <h1 class="pull-left">Eventos</h1>
                    <div class="float-right raw-margin-top-24 raw-margin-left-24">
                        {!! Form::open(['route' => 'eventos.search']) !!}
                        <input class="form-control form-inline pull-right" name="search" placeholder="Procurar">
                        {!! Form::close() !!}
                    </div>
                    <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('admin.eventos.create') !!}">Adicionar novo</a>
                </div>
            </div>

                <div class="card-body">
                    <div class="col-md-12">
                        @if ($eventos->isEmpty())
                            <div class="well text-center">Nenhum evento encontrado.</div>
                        @else
                            <table class="table table-striped">
                                <thead>
                                    <th>Nome</th>
                                    <th class="text-right" width="300px">Ação</th>
                                </thead>
                                <tbody>
                                    @foreach($eventos as $evento)
                                        <tr>
                                            <td>
                                                <a href="{!! route('admin.eventos.edit', [$evento->id]) !!}">{{ $evento->nome }} - {{ $evento->time_a->nome }} X {{ $evento->time_b->nome }}</a>
                                            </td>
                                            <td class="text-right">
                                                <form method="post" action="{!! route('admin.eventos.destroy', [$evento->id]) !!}">
                                                    {!! csrf_field() !!}
                                                    {!! method_field('DELETE') !!}
                                                    <button class="btn btn-danger btn-sm float-right" type="submit" onclick="return confirm('Tem certeza de que deseja excluir este evento?')"><i class="fa fa-trash"></i> Excluir</button>
                                                </form>
                                                <a class="btn btn-success btn-sm float-right raw-margin-right-16" href="{!! route('admin.eventos.copy', [$evento->id]) !!}"><i class="fa fa-copy"></i> Copiar</a>
                                                <a class="btn btn-default btn-sm float-right raw-margin-right-16" href="{!! route('admin.eventos.edit', [$evento->id]) !!}"><i class="fa fa-pencil"></i> Editar</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                    </div>
                </div>
           </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            {!! $eventos; !!}
        </div>
    </div>

@stop

resources/views/admin/eventos/show.blade.php
@extends('dashboard', ['pageTitle' => 'Eventos &raquo; Show'])

@section('content')

    <div class="container">
        <div class="col-md-12">

        <!-- Put fields here -->

        </div>
    </div>

@stop