routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a given Closure or controller and enjoy the fresh air.
|
*/

/*
|--------------------------------------------------------------------------
| Welcome Page
|--------------------------------------------------------------------------
*/

Route::get('/', 'PagesController@home');

/*
|--------------------------------------------------------------------------
| Login/ Logout/ Password
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Registration & Activation
|--------------------------------------------------------------------------
*/
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::get('activate/token/{token}', 'Auth\ActivateController@activate');
Route::group(['middleware' => ['auth']], function () {
    Route::get('activate', 'Auth\ActivateController@showActivate');
    Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['auth', 'active']], function () {

    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('/dashboard', 'PagesController@dashboard');

    /*
    |--------------------------------------------------------------------------
    | Team Routes
    |--------------------------------------------------------------------------
    */

    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');

    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

        Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

        /*
        |--------------------------------------------------------------------------
        | Users
        |--------------------------------------------------------------------------
        */
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');

        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

        /*
        |--------------------------------------------------------------------------
        | Time Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('times', 'TimesController', ['except' => ['show']]);
        Route::post('times/search', [
            'as' => 'times.search',
            'uses' => 'TimesController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | Evento Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('eventos', 'EventosController', ['except' => ['show']])->names('admin.eventos');
        Route::get('eventos/{id}/copy', 'EventosController@copy')->name('admin.eventos.copy');
        Route::post('eventos/search', [
            'as' => 'admin.eventos.search',
            'uses' => 'EventosController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | ListaNegra Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('lista_negras', 'ListaNegrasController', ['except' => ['show']]);
        Route::get('lista_negras/server/sync', 'ListaNegrasController@sync')->name('lista_negras.sync');
        Route::post('lista_negras/search', [
            'as' => 'lista_negras.search',
            'uses' => 'ListaNegrasController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | RegistroEvento Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('registro_eventos', 'RegistroEventosController', ['except' => ['destroy']])->names('admin.registro_eventos');
        Route::post('registro_eventos/search', [
            'as' => 'admin.registro_eventos.search',
            'uses' => 'RegistroEventosController@search'
        ]);
        Route::get('registro_eventos/valid/ingress/valid-ingress', [
            'as' => 'admin.registro_eventos.search.view',
            'uses' => 'RegistroEventosController@searchView'
        ]);


        /*
        |--------------------------------------------------------------------------
        | Estadio Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('estadios', 'EstadiosController', ['except' => ['show']]);
        Route::post('estadios/search', [
            'as' => 'estadios.search',
            'uses' => 'EstadiosController@search'
        ]);
    });

    /*
    |--------------------------------------------------------------------------
    | RegistroEvento Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('registro_eventos', 'RegistroEventosController');
    Route::get('registro_eventos', 'RegistroEventosController@index')->name('pagseguro.redirect');
    Route::post('registro_eventos/search', [
        'as' => 'registro_eventos.search',
        'uses' => 'RegistroEventosController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Dependete Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('dependetes', 'DependetesController', ['except' => ['show']]);
    Route::post('dependetes/search', [
        'as' => 'dependetes.search',
        'uses' => 'DependetesController@search'
    ]);




});

/*
|--------------------------------------------------------------------------
| Evento Routes
|--------------------------------------------------------------------------
*/
Route::resource('eventos', 'EventosController', ['only' => ['show']]);
Route::post('eventos/search', [
    'as' => 'eventos.search',
    'uses' => 'EventosController@search'
]);

Route::post('/pagseguro/notification', [
    'uses' => '\laravel\pagseguro\Platform\Laravel5\NotificationController@notification',
    'as' => 'pagseguro.notification',
]);

app/Models/Team.php
<?php

namespace App\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Team extends Model
{
    use SoftDeletes;

    public $table = "teams";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
        'user_id',
        'name',
    ];

    public static $rules = [
        'name' => 'required|unique:teams'
    ];

    public function members()
    {
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Gate;
use Exception;
use Illuminate\Http\Request;
use App\Services\TeamService;
use App\Http\Requests\TeamCreateRequest;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserInviteRequest;
use App\Http\Requests\TeamUpdateRequest;

class TeamController extends Controller
{
    public function __construct(TeamService $teamService)
    {
        $this->service = $teamService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $teams = $this->service->paginated($request->user()->id);
        return view('team.index')->with('teams', $teams);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $teams = $this->service->search($request->user()->id, $request->search);
        return view('team.index')->with('teams', $teams);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('team.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\TeamCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TeamCreateRequest $request)
    {
        try {
            $result = $this->service->create(Auth::id(), $request->except('_token'));

            if ($result) {
                return redirect('teams/'.$result->id.'/edit')->with('message', 'Successfully created');
            }

            return redirect('teams')->with('message', 'Failed to create');
        } catch (Exception $e) {
            return back()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified team.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showByName($name)
    {
        $team = $this->service->findByName($name);

        if (Gate::allows('team-member', [$team, Auth::user()])) {
            return view('team.show')->with('team', $team);
        }

        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $team = $this->service->find($id);
        return view('team.edit')->with('team', $team);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TeamUpdateRequest $request, $id)
    {
        try {
            $result = $this->service->update($id, $request->except('_token'));

            if ($result) {
                return back()->with('message', 'Successfully updated');
            }

            return back()->with('message', 'Failed to update');
        } catch (Exception $e) {
            return back()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $result = $this->service->destroy(Auth::user(), $id);

            if ($result) {
                return redirect('teams')->with('message', 'Successfully deleted');
            }

            return redirect('teams')->with('message', 'Failed to delete');
        } catch (Exception $e) {
            return back()->withErrors($e->getMessage());
        }
    }

    /**
     * Invite a team member
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function inviteMember(UserInviteRequest $request, $id)
    {
        try {
            $result = $this->service->invite(Auth::user(), $id, $request->email);

            if ($result) {
                return back()->with('message', 'Successfully invited member');
            }

            return back()->with('message', 'Failed to invite member - they may already be a member');
        } catch (Exception $e) {
            return back()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove a team member
     *
     * @param  int  $userId
     * @return \Illuminate\Http\Response
     */
    public function removeMember($id, $userId)
    {
        try {
            $result = $this->service->remove(Auth::user(), $id, $userId);

            if ($result) {
                return back()->with('message', 'Successfully removed member');
            }

            return back()->with('message', 'Failed to remove member');
        } catch (Exception $e) {
            return back()->withErrors($e->getMessage());
        }
    }
}

resources/views/team/create.blade.php
@extends('dashboard')

@section('pageTitle') Teams: Create @stop

@section('content')

    <div class="col-md-4 m-auto">
        <div class="card">
            <div class="card-body">
                <div class="col-md-offset-4">
                    <form method="post" action="{{ route('teams.store') }}">
                        {!! csrf_field() !!}

                        @form_maker_table("teams", ['name' => 'string'])
                        <div class="raw-margin-top-24">
                            <a class="btn btn-secondary pull-left" href="{{ url('teams') }}">Cancel</a>
                            <button class="btn btn-primary pull-right" type="submit">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@stop

resources/views/team/edit.blade.php
@extends('dashboard')

@section('pageTitle') Teams: Edit @stop

@section('content')
    <div class="col-md-8 m-auto">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <div class="raw-margin-bottom-24">
                            <form method="post" action="{{ url('teams/'.$team->id) }}">
                                {!! csrf_field() !!}
                                {!! method_field('PATCH') !!}

                                @form_maker_object($team, ['name' => 'string'])

                                <div class="raw-margin-top-24">
                                    <a class="btn btn-secondary pull-left" href="{{ url('teams') }}">Cancel</a>
                                    <button class="btn btn-primary pull-right" type="submit">Save</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <div class="raw-margin-bottom-24">
                            @if (Auth::user()->isTeamAdmin($team->id))
                                <form method="post" action="{{ url('teams/'.$team->id.'/invite') }}">
                                    {!! csrf_field() !!}
                                    <div class="form-group">
                                        <label>Invite a new member</label>
                                        <input class="form-control" type="email" name="email" placeholder="Email">
                                    </div>
                                    <button class="btn btn-primary pull-right" type="submit">Invite</button>
                                </form>
                            @endif
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8 m-auto">
        <div class="card raw-margin-top-24">
            @if (Auth::user()->isTeamAdmin($team->id))
                <div class="col-md-12 raw-margin-top-24">
                    <h2 class="text-left">Members</h2>
                    @if ($team->members->isEmpty())
                        <div class="col-md-12 raw-margin-bottom-24">
                            <div class="well text-center">No members found.</div>
                        </div>
                    @else
                        <table class="table table-striped">
                            <thead>
                            <th>Name</th>
                            <th class="text-right">Action</th>
                            </thead>
                            <tbody>
                            @foreach($team->members as $member)
                                <tr>
                                    <td>{{ $member->name }}</td>
                                    <td>
                                        @if (! $member->isTeamAdmin($team->id))
                                            <a class="btn btn-danger pull-right btn-xs"
                                               href="{{ url('teams/'.$team->id.'/remove/'.$member->id) }}"
                                               onclick="return confirm('Are you sure you want to remove this member?')">Remove</a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @endif
                </div>
            @endif
        </div>
    </div>
@stop

resources/views/team/index.blade.php
@extends('dashboard')

@section('pageTitle') Teams @stop

@section('content')
    <div class="col-md-8 m-auto">
        <ddiv class="card">

            <div class="card-header">
                <div class="col-md-12">
                    <div class="btn-toolbar justify-content-between">
                        <a class="btn btn-primary raw-margin-right-8" href="{{ url('teams/create') }}">Create Team</a>
                        <form class="form-inline" method="post" action="/teams/search">
                            {!! csrf_field() !!}
                            <input class="form-control mr-sm-2" name="search" type="search" value="{{ request('search') }}" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <div class="col-md-12 raw-margin-top-24">
                    @if ($teams->isEmpty())
                        <div class="card card-default text-center">
                            <div class="card-body">
                                <span>No teams found.</span>
                            </div>
                        </div>
                    @else
                        <table class="table table-striped">
                            <thead>
                            <th>Name</th>
                            <th width="165px" class="text-right">Action</th>
                            </thead>
                            <tbody>
                            @foreach($teams as $team)
                                <tr>
                                    <td>{{ $team->name }}</td>
                                    <td>
                                        <div class="btn-toolbar pull-right">
                                            <a class="btn btn-outline-primary btn-sm raw-margin-right-8" href="{!! route('teams.edit', [$team->id]) !!}"><i class="fa fa-edit"></i> Edit</a>
                                            <form class="form" method="post" action="{!! url('teams/'.$team->id) !!}">
                                                {!! csrf_field() !!}
                                                {!! method_field('DELETE') !!}
                                                <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('Are you sure you want to delete this team?')"><i class="fa fa-trash"></i> Delete</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        <div class="row text-center">
                            {!! $teams; !!}
                        </div>
                    @endif
                </div>
            </div>
        </ddiv>
    </div>

@stop

resources/views/team/show.blade.php
<div class="container">

    {{ $team->name }}

    <h2>Members</h2>
    <table>
        <thead>
            <th>Name</th>
        </thead>
        <tbody>
            @foreach($team->members as $member)
                <tr>
                    <td>{{ $member->name }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

</div>