routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a given Closure or controller and enjoy the fresh air.
|
*/

/*
|--------------------------------------------------------------------------
| Welcome Page
|--------------------------------------------------------------------------
*/

Route::get('/', 'PagesController@home');

/*
|--------------------------------------------------------------------------
| Login/ Logout/ Password
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Registration & Activation
|--------------------------------------------------------------------------
*/
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::get('activate/token/{token}', 'Auth\ActivateController@activate');
Route::group(['middleware' => ['auth']], function () {
    Route::get('activate', 'Auth\ActivateController@showActivate');
    Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['auth', 'active']], function () {

    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('/dashboard', 'PagesController@dashboard');

    /*
    |--------------------------------------------------------------------------
    | Team Routes
    |--------------------------------------------------------------------------
    */

    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');

    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

        Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');

        /*
        |--------------------------------------------------------------------------
        | Users
        |--------------------------------------------------------------------------
        */
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');

        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');

        /*
        |--------------------------------------------------------------------------
        | Time Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('times', 'TimesController', ['except' => ['show']]);
        Route::post('times/search', [
            'as' => 'times.search',
            'uses' => 'TimesController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | Evento Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('eventos', 'EventosController', ['except' => ['show']])->names('admin.eventos');
        Route::get('eventos/{id}/copy', 'EventosController@copy')->name('admin.eventos.copy');
        Route::post('eventos/search', [
            'as' => 'admin.eventos.search',
            'uses' => 'EventosController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | ListaNegra Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('lista_negras', 'ListaNegrasController', ['except' => ['show']]);
        Route::get('lista_negras/server/sync', 'ListaNegrasController@sync')->name('lista_negras.sync');
        Route::post('lista_negras/search', [
            'as' => 'lista_negras.search',
            'uses' => 'ListaNegrasController@search'
        ]);

        /*
        |--------------------------------------------------------------------------
        | RegistroEvento Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('registro_eventos', 'RegistroEventosController', ['except' => ['destroy']])->names('admin.registro_eventos');
        Route::post('registro_eventos/search', [
            'as' => 'admin.registro_eventos.search',
            'uses' => 'RegistroEventosController@search'
        ]);
        Route::get('registro_eventos/valid/ingress/valid-ingress', [
            'as' => 'admin.registro_eventos.search.view',
            'uses' => 'RegistroEventosController@searchView'
        ]);


        /*
        |--------------------------------------------------------------------------
        | Estadio Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('estadios', 'EstadiosController', ['except' => ['show']]);
        Route::post('estadios/search', [
            'as' => 'estadios.search',
            'uses' => 'EstadiosController@search'
        ]);
    });

    /*
    |--------------------------------------------------------------------------
    | RegistroEvento Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('registro_eventos', 'RegistroEventosController');
    Route::get('registro_eventos', 'RegistroEventosController@index')->name('pagseguro.redirect');
    Route::post('registro_eventos/search', [
        'as' => 'registro_eventos.search',
        'uses' => 'RegistroEventosController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Dependete Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('dependetes', 'DependetesController', ['except' => ['show']]);
    Route::post('dependetes/search', [
        'as' => 'dependetes.search',
        'uses' => 'DependetesController@search'
    ]);




});

/*
|--------------------------------------------------------------------------
| Evento Routes
|--------------------------------------------------------------------------
*/
Route::resource('eventos', 'EventosController', ['only' => ['show']]);
Route::post('eventos/search', [
    'as' => 'eventos.search',
    'uses' => 'EventosController@search'
]);

Route::post('/pagseguro/notification', [
    'uses' => '\laravel\pagseguro\Platform\Laravel5\NotificationController@notification',
    'as' => 'pagseguro.notification',
]);

app/Models/Estadio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Estadio extends Model
{
    use SoftDeletes;

    public $table = "estadios";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
		'id',
		'nome',

    ];

    public static $rules = [
        // create rules
        'nome' => 'required'
    ];

    public function getEstadios() {
        $aaray = ['nome' => '<< Selecione >>', 'id' => null];
        return $this->get()->add((new Estadio($aaray)))->sortBy('id');
    }

    // Estadio 
}

app/Http/Controllers/Admin/EstadiosController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\EstadioService;
use App\Http\Requests\EstadioCreateRequest;
use App\Http\Requests\EstadioUpdateRequest;

/**
 * @property EstadioService service
 */
class EstadiosController extends Controller
{
    public function __construct(EstadioService $estadio_service)
    {
        $this->service = $estadio_service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $estadios = $this->service->paginated();
        return view('admin.estadios.index')->with('estadios', $estadios);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $estadios = $this->service->search($request->search);
        return view('admin.estadios.index')->with('estadios', $estadios);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.estadios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\EstadioCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EstadioCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('estadios.edit', ['id' => $result->id]))->with('message', 'O estádio foi criado com sucesso');
        }

        return redirect(route('estadios.index'))->withErrors('Failed to create');
    }

    /**
     * Display the estadio.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $estadio = $this->service->find($id);
        return view('admin.estadios.show')->with('estadio', $estadio);
    }

    /**
     * Show the form for editing the estadio.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $estadio = $this->service->find($id);
        return view('admin.estadios.edit')->with('estadio', $estadio);
    }

    /**
     * Update the estadios in storage.
     *
     * @param  App\Http\Requests\EstadioUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EstadioUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Nome do estádio foi alterado com sucesso');
        }

        return back()->withErrors('Failed to update');
    }

    /**
     * Remove the estadios from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('estadios.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('estadios.index'))->withErrors('Failed to delete');
    }
}

resources/views/admin/estadios/create.blade.php
@extends('layouts.app')

@section('pageTitle') Estádios &raquo; Criar @stop

@section('content')
    <div class="col-md-6 m-auto">
        <div class="card">
            <div class="card-header">
                <div class="col-md-12">
                    <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                        {!! Form::open(['route' => 'estadios.search']) !!}
                        <input class="form-control form-inline pull-right" name="search" placeholder="Procurar">
                        {!! Form::close() !!}
                    </div>
                    <h1 class="pull-left">Estádios: Criar</h1>
                </div>
            </div>
            <div class="card-body">
                <div class="col-md-12">

                    {!! Form::open(['route' => 'estadios.store']) !!}

                   <div class="form-row raw-margin-bottom-15">
                       @form_maker_table("estadios")
                   </div>

                    {!! Form::submit('Salvar', ['class' => 'btn btn-primary pull-right']) !!}
                    <a href="{{ url('admin/estadios') }}" class="btn btn-secondary"> Cancelar</a>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>

@stop

resources/views/admin/estadios/edit.blade.php
@extends('layouts.app')

@section('pageTitle') Estádios &raquo; Editar @stop

@section('content')
<div class="col-md-6 m-auto">
    <div class="card">
        <div class="card-header">
            <div class="col-md-12">
                <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                    {!! Form::open(['route' => 'estadios.search']) !!}
                    <input class="form-control form-inline pull-right" name="search" placeholder="Procurar">
                    {!! Form::close() !!}
                </div>
                <h1 class="pull-left">Estádios: Editar</h1>
                <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('estadios.create') !!}">Adicionar novo</a>
            </div>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                {!! Form::model($estadio, ['route' => ['estadios.update', $estadio->id], 'method' => 'patch']) !!}

               <div class="form-row raw-margin-bottom-15">
                   @form_maker_object($estadio, FormMaker::getTableColumns('estadios'))
               </div>

                {!! Form::submit('Atualizar', ['class' => 'btn btn-primary pull-right']) !!}
                <a href="{{ url('admin/estadios') }}" class="btn btn-secondary">Voltar</a>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

@stop

resources/views/admin/estadios/index.blade.php
@extends('layouts.app')

@section('pageTitle') Estádios &raquo; Índice @stop

@section('content')
<div class="col-md-8 m-auto">
        <div class="card">
            <div class="card-header">
                <div class="col-md-12">
                    <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                        {!! Form::open(['route' => 'estadios.search']) !!}
                        <input class="form-control form-inline pull-right" name="search" placeholder="Procurar">
                        {!! Form::close() !!}
                    </div>
                    <h1 class="pull-left">Estádios</h1>
                    <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('estadios.create') !!}">Adicionar novo</a>
                </div>
            </div>

                <div class="card-body">
                    <div class="col-md-12">
                        @if ($estadios->isEmpty())
                            <div class="well text-center">Nenhum estádio encontrado.</div>
                        @else
                            <table class="table table-striped">
                                <thead>
                                    <th>Nome</th>
                                    <th class="text-right" width="200px">Ação</th>
                                </thead>
                                <tbody>
                                    @foreach($estadios as $estadio)
                                        <tr>
                                            <td>
                                                <a href="{!! route('estadios.edit', [$estadio->id]) !!}">{{ $estadio->nome }}</a>
                                            </td>
                                            <td class="text-right">
                                                <form method="post" action="{!! route('estadios.destroy', [$estadio->id]) !!}">
                                                    {!! csrf_field() !!}
                                                    {!! method_field('DELETE') !!}
                                                    <button class="btn btn-danger btn-sm float-right" type="submit" onclick="return confirm('Tem certeza de que deseja excluir este estádio?')"><i class="fa fa-trash"></i> Excluir</button>
                                                </form>
                                                <a class="btn btn-default btn-sm float-right raw-margin-right-16" href="{!! route('estadios.edit', [$estadio->id]) !!}"><i class="fa fa-pencil"></i> Editar</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                    </div>
                </div>
           </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            {!! $estadios; !!}
        </div>
    </div>

@stop

resources/views/admin/estadios/show.blade.php
@extends('dashboard', ['pageTitle' => 'Estadios &raquo; Show'])

@section('content')

    <div class="container">
        <div class="col-md-12">

        <!-- Put fields here -->

        </div>
    </div>

@stop